<SCRIPT language=JavaScript> 
 
function password() { 
 
var testV = 1; 
 
var pass1 = prompt('请输入密码:',''); 
 
while (testV < 3) { 
 
if (!pass1) 
 
history.go(-1); 
 
if (pass1 == w1856444"这里输入你想设置的密码") { 
 
alert('密码正确!'); 
 
break; 
 
} 
 
testV+=-1; 
 
var pass1 = prompt('密码错误!请重新输入:'); 
 
} 
 
if (pass1!="password" & testV ==3) 
 
history.go(-1); 
 
return " "; 
 
} 
 
document.write(password()); 
 
</SCRIPT>

# Site settings
title: 理想之土，幻想之境 # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "一片自由的净土"  # 一句话描述你的博客
baseurl: ""
url: "ziyzk.online"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "ZIK" # 填写作者信息：名字
  email: master@ziyzk.online # 填写作者信息：邮箱
  bio: "某社畜的小窝" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

# SNS settings
RSS: true

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "ZIK" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name : disqus_JJVCXz0qZ5 # 填写你的 disqus id
  disqus :
      short_name : disqus_JJVCXz0qZ5 # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: G-LJRQX7RK0J # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

