# Site settings
title: 理想之土，幻想之境 # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "一片自由的净土"  # 一句话描述你的博客
baseurl: ""
url: "ziyzk.online"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "ZIYZK" # 填写作者信息：名字
  email: w1856444@outlook.com # 填写作者信息：邮箱
  bio: "某高中社畜的小窝" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: ZIYZK 
github_username: ziyzk
facebook_username: Zhang Yike
weibo_username: 
zhihu_username: jie-gua-66

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "ZIYZK" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
# Disqus（https://disqus.com/）
disqus_username: disqus_JJVCXz0qZ5

# Analytics and webmaster tools stuff goes here
ga_track_id: 'G-LJRQX7RK0J'            # 你用Google账号去注册一个就会给你一个这样的id
ga_domain: ziyzk.online			# 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto。:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
